// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC-sZrx4KLwWxxtJ__x7HtNorjzHRKMqE',
    appId: '1:409465427852:web:ada1069fcfce717beda8a9',
    messagingSenderId: '409465427852',
    projectId: 'project-f6c8a027-6a46-4d5c-902',
    authDomain: 'project-f6c8a027-6a46-4d5c-902.firebaseapp.com',
    storageBucket: 'project-f6c8a027-6a46-4d5c-902.firebasestorage.app',
    measurementId: 'G-Z5QP6DFTC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAumAIvBIWNpvbaCuA9igQN2RWKyT6iWLw',
    appId: '1:409465427852:android:6a2910447a3267feeda8a9',
    messagingSenderId: '409465427852',
    projectId: 'project-f6c8a027-6a46-4d5c-902',
    storageBucket: 'project-f6c8a027-6a46-4d5c-902.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBvG60OVU2ePVqPQPCQUZ1g1vzqyyBV4E',
    appId: '1:409465427852:ios:bd766f9140017372eda8a9',
    messagingSenderId: '409465427852',
    projectId: 'project-f6c8a027-6a46-4d5c-902',
    storageBucket: 'project-f6c8a027-6a46-4d5c-902.firebasestorage.app',
    iosBundleId: 'com.example.filmio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBvG60OVU2ePVqPQPCQUZ1g1vzqyyBV4E',
    appId: '1:409465427852:ios:bd766f9140017372eda8a9',
    messagingSenderId: '409465427852',
    projectId: 'project-f6c8a027-6a46-4d5c-902',
    storageBucket: 'project-f6c8a027-6a46-4d5c-902.firebasestorage.app',
    iosBundleId: 'com.example.filmio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDC-sZrx4KLwWxxtJ__x7HtNorjzHRKMqE',
    appId: '1:409465427852:web:5b60653180e6c527eda8a9',
    messagingSenderId: '409465427852',
    projectId: 'project-f6c8a027-6a46-4d5c-902',
    authDomain: 'project-f6c8a027-6a46-4d5c-902.firebaseapp.com',
    storageBucket: 'project-f6c8a027-6a46-4d5c-902.firebasestorage.app',
    measurementId: 'G-19LV33BLXM',
  );
}
