// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe0kjS7DEForHkJ-Od3eaDHcax87nk-i8',
    appId: '1:104069586840:web:dc72fb98f3073b32f415ed',
    messagingSenderId: '104069586840',
    projectId: 'filmio-01',
    authDomain: 'filmio-01.firebaseapp.com',
    storageBucket: 'filmio-01.firebasestorage.app',
    measurementId: 'G-2F407J4Z3G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK52ApeeLJTsmYh_rin5vC4Rc6TsUPUgU',
    appId: '1:104069586840:android:713dc055e6d3d45ef415ed',
    messagingSenderId: '104069586840',
    projectId: 'filmio-01',
    storageBucket: 'filmio-01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWtEIl8IWnM0GH07YIE4sqy75d0lpncts',
    appId: '1:104069586840:ios:aabea81b489902aef415ed',
    messagingSenderId: '104069586840',
    projectId: 'filmio-01',
    storageBucket: 'filmio-01.firebasestorage.app',
    iosBundleId: 'com.example.filmio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWtEIl8IWnM0GH07YIE4sqy75d0lpncts',
    appId: '1:104069586840:ios:aabea81b489902aef415ed',
    messagingSenderId: '104069586840',
    projectId: 'filmio-01',
    storageBucket: 'filmio-01.firebasestorage.app',
    iosBundleId: 'com.example.filmio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAe0kjS7DEForHkJ-Od3eaDHcax87nk-i8',
    appId: '1:104069586840:web:e054c0784e11807ef415ed',
    messagingSenderId: '104069586840',
    projectId: 'filmio-01',
    authDomain: 'filmio-01.firebaseapp.com',
    storageBucket: 'filmio-01.firebasestorage.app',
    measurementId: 'G-7C1L6HKYYW',
  );
}
